name: 'Azure Storage Action'
description: 'You can automate your workflow to deploy files to Azure Blob Storage Container without Azure Credentials'
inputs:
  connection-string: 
    description: 'Connection String of the Azure Storage Container'
    required: true
  folder: 
    description: 'Folder what contains the files for upload to Storage Container'
    required: false
  blob-container-name: 
    description: 'Name of Blob Container Storage'
    required: false
  public-access-policy: 
    description: 'Access Policy to update in the Container'
    required: false
  enabled-static-website: 
    description: 'Enabled static website'
    required: false
  index-file: 
    description: 'Index file for the static site'
    required: false
  error-file: 
    description: '404 Error file for the static site'
    required: false
  remove-existing-files: 
    description: 'If the existing files should be removed or not'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
