name: Build and Test

on:
  pull_request:
  push:
    branches:
      - test
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: 'Build and Test'
        working-directory: 'src'
        run: |
          npm install
          npm test --if-exists
           
