on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - run: |
        npm i
        npm run build
        
    - uses: tibor19/Azure-Storage-Action@node-only
      with:
        enabled-static-website: 'true'
        folder: 'build'
        connection-string: ${{ secrets.CONNECTION_STRING }}